name: sonar-env

dependencies:
  - shapely=1.8.4
  - rasterio=1.2.10
  - pillow=9.2.0
  - pathlib=1.0.1
  - pandas=1.4.4
  - opencv=4.6.0
  - numpy=1.23.1
  - matplotlib=3.5.2
  - geopandas=0.9.0
  - gdal=3.0.2
  - configparser=5.0.2
  - brotlipy=0.7.0
  - pip=22.2.2
  - pip:
    - geopy==2.2.0
    - contextily==1.2.0
    - pyproj==3.3.1
    - urllib3==1.26.10
